services:
  my-app:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_DB_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_ADMIN_PASSWORD}

  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo-db
    depends_on:
      - "mongo-db"
